repositories:
  - name: open-webui
    url: https://open-webui.github.io/helm-charts

releases:
  - name: open-webui
    namespace: open-webui
    chart: open-webui/open-webui
    version: 5.25.0
    values:
      - ollama:
          enabled: false
      - persistence:
          storageClass: nfs-csi
      - ingress:
          enabled: true
          class: nginx
          host: open-webui.b-rad.dev
          tls: true
          secretName: null
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/icon: "https://open-webui.b-rad.dev/static/splash.png"
            forecastle.stakater.com/group: "AI"
      - extraEnvVars:
          - name: OPENAI_API_BASE_URL
            value: http://ollama.ollama:11434/v1