repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.12.1
    values:
      - controller:
          extraArgs:
            default-ssl-certificate: "cert-manager/nginx-tls" #single wildcard cert for all subdomains
          config:
            proxy-body-size: 50m