repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.17.1
    values:
      # kubectl -n cert-manager create secret generic acme-dns --from-file acmedns.json
      - crds:
          enabled: true