repositories:
  - name: twin
    url: https://twin.github.io/helm-charts

releases:
  - name: gatus
    namespace: gatus
    chart: twin/gatus
    version: 1.2.0
    values:
      - ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - gatus.b-rad.dev
          tls:
            - hosts:
                - gatus.b-rad.dev
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/icon: "https://gatus.b-rad.dev/img/logo.svg"
            forecastle.stakater.com/group: "Monitoring"
      - config:
          endpoints:
            - name: Emby
              url: http://emby.emby:8096
              ui:
                hide-hostname: true
              interval: 5m
              conditions:
                - "[STATUS] == 200"
            - name: Medusa
              url: http://medusa.medusa:8081
              ui:
                hide-hostname: true
              interval: 5m
              conditions:
                - "[STATUS] == 200"
            - name: Ntfy
              url: http://ntfy.ntfy
              ui:
                hide-hostname: true
              interval: 5m
              conditions:
                - "[STATUS] == 200"
            - name: Ollama
              url: http://ollama.ollama:11434
              ui:
                hide-hostname: true
              interval: 5m
              conditions:
                - "[STATUS] == 200"
            - name: Open WebUI
              url: http://open-webui.open-webui
              ui:
                hide-hostname: true
              interval: 5m
              conditions:
                - "[STATUS] == 200"
            - name: Public IP
              url: https://icanhazip.com
              ui:
                hide-hostname: true
              interval: 5m
              conditions:
                - "[BODY] == 76.104.202.224"
            - name: qBittorrent
              url: http://qbittorrent.qbittorrent:8080
              ui:
                hide-hostname: true
              interval: 5m
              conditions:
                - "[STATUS] == 200"
            - name: ComfyUI
              url: http://comfyui.comfyui:8188
              ui:
                hide-hostname: true
              interval: 5m
              conditions:
                - "[STATUS] == 200"
            - name: ComfyUI - 4090
              url: http://comfyui-4090.default
              ui:
                hide-hostname: true
              interval: 5m
              conditions:
                - "[STATUS] == 200"