releases:
  - name: comfyui-discord-bot
    namespace: comfyui-discord-bot
    chart: ../comfyui-discord-bot
    values:
      - image:
          tag: 0.15.0
      - env:
          - name: BOT_TYPE
            value: "PRODUCTION"
          - name: VERSION
            value: "0.15.0"
          - name: COMFYUI_ADDRESS
            value: "comfyui-4090.default,comfyui.comfyui:8188"
          - name: COMFYUI_MODEL_CHECKPOINT_PATH
            value: "/mnt/comfyui-models/checkpoints"
          - name: DEVELOPMENT_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: bot-tokens
                key: development
          - name: PRODUCTION_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: bot-tokens
                key: production
      - volumes:
          - name: comfyui-data
            persistentVolumeClaim:
              claimName: comfyui-data
          - name: bot-data
            persistentVolumeClaim:
              claimName: comfyui-discord-bot
      - volumeMounts:
          - name: comfyui-data
            mountPath: /mnt/comfyui-models
            subPath: comfyui-comfyui/ComfyUI/models
          - name: bot-data
            mountPath: /app/src/models
            subPath: production/models
          - name: bot-data
            mountPath: /app/src/workflows
            subPath: production/workflows
      - dev:
          image:
            tag: 20251123-190144
          env:
            - name: BOT_TYPE
              value: "DEVELOPMENT"
            - name: VERSION
              value: "0.16.0-SNAPSHOT"
            - name: COMFYUI_ADDRESS
              value: "comfyui-4090.default,comfyui.comfyui:8188"
            - name: COMFYUI_MODEL_CHECKPOINT_PATH
              value: "/mnt/comfyui-models/checkpoints"
            - name: DEVELOPMENT_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-tokens
                  key: development
            - name: PRODUCTION_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-tokens
                  key: production
          volumes:
            - name: comfyui-data
              persistentVolumeClaim:
                claimName: comfyui-data
            - name: bot-data
              persistentVolumeClaim:
                claimName: comfyui-discord-bot
          volumeMounts:
            - name: comfyui-data
              mountPath: /mnt/comfyui-models
              subPath: comfyui-comfyui/ComfyUI/models
            - name: bot-data
              mountPath: /app/src/models
              subPath: development/models
            - name: bot-data
              mountPath: /app/src/workflows
              subPath: development/workflows