releases:
  - name: comfyui-discord-bot
    namespace: comfyui-discord-bot
    chart: ../comfyui-discord-bot
    values:
      - image:
          tag: 20250502-203917
      - env:
          - name: BOT_TYPE
            value: "PRODUCTION"
          - name: VERSION
            value: "0.10.0"
          - name: COMFYUI_ADDRESS
            value: "comfyui.comfyui:8188"
          - name: DEVELOPMENT_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: bot-tokens
                key: development
          - name: PRODUCTION_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: bot-tokens
                key: production
      - volumes:
          - name: comfyui-data
            persistentVolumeClaim:
              claimName: comfyui-data
      - volumeMounts:
          - name: comfyui-data
            mountPath: /mnt/comfyui-models
            subPath: comfyui-comfyui/ComfyUI/models
      - dev:
          image:
            tag: 20250502-203917
          env:
            - name: BOT_TYPE
              value: "DEVELOPMENT"
            - name: VERSION
              value: "0.10.0"
            - name: COMFYUI_ADDRESS
              value: "comfyui.comfyui:8188"
            - name: DEVELOPMENT_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-tokens
                  key: development
            - name: PRODUCTION_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-tokens
                  key: production
          volumes:
            - name: comfyui-data
              persistentVolumeClaim:
                claimName: comfyui-data
          volumeMounts:
            - name: comfyui-data
              mountPath: /mnt/comfyui-models
              subPath: comfyui-comfyui/ComfyUI/models