repositories:
  - name: nfd
    url: https://kubernetes-sigs.github.io/node-feature-discovery/charts

releases:
  - name: nfd
    namespace: node-feature-discovery
    chart: nfd/node-feature-discovery
    version: 0.17.3
    values:
      - worker:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: NotIn
                        values:
                          - pi2-1gb-01