repositories:
  - name: gitea-charts
    url: https://dl.gitea.com/charts/

releases:
  - name: gitea
    namespace: gitea
    chart: gitea-charts/gitea
    version: 12.6.0
    values:
      - ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 4G
          hosts:
            - host: gitea.b-rad.dev
          tls:
            - hosts:
                - gitea.b-rad.dev
      - service:
          ssh:
            type: LoadBalancer
            externalTrafficPolicy: Local
            port: 2222
      - persistence:
          enabled: true
          storageClass: nfs-csi
          accessModes: ["ReadWriteMany"]
      - postgresql:
          enabled: false
      - postgresql-ha:
          enabled: false
      - gitea:
          config:
            database:
              DB_TYPE: postgres
              HOST: 10.0.0.15
              NAME: giteadb
              USER: gitea
              SCHEMA: gitea
          additionalConfigFromEnvs:
            - name: GITEA__DATABASE__PASSWD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: GITEA__service__DISABLE_REGISTRATION
              value: "true"
            - name: FOO
              value: "bar"
  - name: gitea-actions
    namespace: gitea
    chart: gitea-charts/actions
    version: v0.1.1
    values:
      - enabled: true
      - giteaRootURL: http://gitea-http:3000
      - existingSecret: runner-secret
      - existingSecretKey: runner-token
      - statefulset:
          dind:
            tag: 29.5.2-dind
#          runner:
#            registry: gitea.b-rad.dev
#            repository: brad/runner-images
#            tag: 20260614-154415