image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: alpine

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  hosts:
    - host: b-rad.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - b-rad.dev

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  annotations: {}
  size: 5Gi #not really respected when using NFS...which I am
  storageClass: nfs-csi

# Additional volumes on the output Deployment definition.
volumes:
  - name: app-data
    persistentVolumeClaim:
      claimName: homepage
  - name: nginx-config
    configMap:
      name: nginx-config

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: app-data
    mountPath: /usr/share/nginx/html
  - name: nginx-config
    mountPath: /etc/nginx/conf.d/default.conf
    subPath: default.conf
    readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80