apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name b-rad.dev;

        root   /usr/share/nginx/html;
        index  index.html;
        ssi on;

        location / {
            try_files $uri $uri/ =404;
        }
    }

