apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name b-rad.dev;

        root   /usr/share/nginx/html;
        index  index.html;
        ssi on;

        location / {
            try_files $uri $uri/ =404;
        }

        location ^~ /images/ai/lora/list/ {
            alias /usr/share/nginx/html/images/ai/lora/;
            autoindex on;
            index off;
        }

        location /images/ai/lora/ {
            index index.html;
        }

        location ~* \.(jpg|jpeg|png|gif|webp|svg)$ {
            expires 30d;
            add_header Cache-Control "public, max-age=2592000, immutable";
        }
    }

