apiVersion: v1
kind: Service
metadata:
  name: {{ include "webtop.fullname" . }}
  labels:
    {{- include "webtop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8082
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "webtop.selectorLabels" . | nindent 4 }}
