apiVersion: v1
kind: PersistentVolume
metadata:
  name: openproject
spec:
  storageClassName: nfs-csi-custom
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.15
    path: /volume1/NFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject
spec:
  storageClassName: nfs-csi-custom
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
