##########################################################
# NOT INSTALLED - Testing concluded, using prod cert now #
##########################################################
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: b-rad-dev-staging
  namespace: cert-manager
spec:
  secretName: nginx-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - 'b-rad.dev'
    - '*.b-rad.dev'