apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: b-rad-dev
  namespace: cert-manager
spec:
  secretName: nginx-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - 'b-rad.dev'
    - '*.b-rad.dev'