CREATE ROLE gitea WITH LOGIN PASSWORD '<REPLACE ME>';
CREATE DATABASE giteadb WITH OWNER gitea TEMPLATE template0 ENCODING UTF8 LC_COLLATE 'en_US.UTF-8' LC_CTYPE 'en_US.UTF-8';
GRANT ALL PRIVILEGES ON DATABASE giteadb TO gitea;
-- \connect giteadb
CREATE SCHEMA gitea;
GRANT ALL PRIVILEGES ON SCHEMA gitea TO gitea;
GRANT ALL PRIVILEGES ON SCHEMA public TO gitea;