repositories:
  - name: nvdp
    url: https://nvidia.github.io/k8s-device-plugin
  - name: ollama-helm
    url: https://otwld.github.io/ollama-helm/

# Fix cuda related errors with:
# kubectl cordon <node>
# sudo systemctl stop k3s
# lsof /dev/nvidia*
# Kill any running processes
# sudo modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia
# sudo modprobe nvidia_drm nvidia_modeset nvidia_uvm nvidia
# sudo systemctl start k3s
# kubectl uncordon <node>

releases:
  - name: nvdp
    namespace: kube-system
    chart: nvdp/nvidia-device-plugin
    version: 0.17.1
#    values:
#      - failOnInitError: true
  - name: ollama
    namespace: ollama
    chart: ollama-helm/ollama
    version: 1.11.0
    values:
      - runtimeClassName: nvidia
      - nodeSelector:
          nvidia.com/gpu.memory: "4096"
      - ollama:
          gpu:
            enabled: true
            type: nvidia
            number: 1
          models:
            pull:
              - deepseek-r1:1.5b
            run:
              - deepseek-r1:1.5b