apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.15
  share: /volume1/NFS
  subDir: "${pvc.metadata.namespace}-${pvc.metadata.name}"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-custom
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.15
  share: /volume1/NFS
  subDir: "${pvc.metadata.name}"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
