{{- if .Values.flareSolverr.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flareSolverr.serviceAccountName" . }}
  labels:
    {{- include "flareSolverr.labels" . | nindent 4 }}
  {{- with .Values.flareSolverr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.flareSolverr.serviceAccount.automount }}
{{- end }}
