apiVersion: v1
kind: Service
metadata:
  name: {{ include "prowlarr.fullname" . }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prowlarr.service.type }}
  ports:
    - port: {{ .Values.prowlarr.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prowlarr.selectorLabels" . | nindent 4 }}
