{{- if .Values.prowlarr.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prowlarr.serviceAccountName" . }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
  {{- with .Values.prowlarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.prowlarr.serviceAccount.automount }}
{{- end }}
