apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}-config
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/

    log_dest stdout

    listener 1883
    allow_anonymous false

    password_file {{ .Values.auth.passwordFilePath }}
