#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: lm-studio
#subsets:
#  - addresses:
#      - ip: 10.0.0.21
#    ports:
#      - port: 1234
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: lm-studio
#spec:
#  ports:
#    - port: 80
#      targetPort: 1234
#---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: comfyui-4090
  labels:
    kubernetes.io/service-name: comfyui-4090
addressType: IPv4
ports:
  - port: 8188
endpoints:
  - addresses:
      - 10.0.0.21
---
apiVersion: v1
kind: Service
metadata:
  name: comfyui-4090
spec:
  ports:
    - port: 80
      targetPort: 8188
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/auth-url: https://login.b-rad.dev/authorize
  name: comfyui-4090
spec:
  ingressClassName: nginx
  rules:
    - host: comfyui-4090.b-rad.dev
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: comfyui-4090
                port:
                  number: 80

  tls:
    - hosts:
        - comfyui-4090.b-rad.dev