image:
  repository: registry.b-rad.dev:443/magicmirror
  pullPolicy: IfNotPresent
  tag: latest # fat does not have `ping` installed, need to create my own docker image

imagePullSecrets:
  - name: registry-credentials

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1000

securityContext: {}

env:
  - name: TZ
    value: America/Los_Angeles

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: false
#  className: nginx
#  annotations:
#    cert-manager.io/cluster-issuer: "letsencrypt-production"
#  hosts:
#    - host: medusa.b-rad.dev
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
#  tls:
#    - hosts:
#        - medusa.b-rad.dev

resources: {}

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteMany
  annotations: {}
  size: 5Gi #not really respected when using NFS...which I am
  storageClass: nfs-csi

# Additional volumes on the output Deployment definition.
volumes:
  - name: app-data
    persistentVolumeClaim:
      claimName: magicmirror

# Need to pre-create these folders to get uid of 1000
volumeMounts:
  - name: app-data
    mountPath: /opt/magic_mirror/config
    subPath: config
  - name: app-data
    mountPath: /opt/magic_mirror/modules
    subPath: modules
  - name: app-data
    mountPath: /opt/magic_mirror/css
    subPath: css

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80