---
# TODO: Remove this, use the nfs-sc.yaml at the "root"
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-basic
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.15
  share: /volume1/NFS
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-data
spec:
  storageClassName: nfs-csi-basic
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.15
    path: /volume1/NFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-data
spec:
  storageClassName: nfs-csi-basic
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
