apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5G
