apiVersion: v2
name: librechat
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: librechat
    version: 1.9.0
    repository: oci://ghcr.io/danny-avila/librechat-chart