---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emby-shows-01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi-custom