apiVersion: v1
kind: Service
metadata:
  name: mcp-gateway
spec:
  type: LoadBalancer
  selector:
    app: mcp-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP